// Permission data defining roles and their permissions
const permissionData = {
    Master: [
      "dashboard.view",
      "calendar.view",
      "email.view",
      "pages.view",
      "auth.view",
      "utility.view",
      "ui.view",
      "forms.view",
      "tables.view",
      "charts.view",
      "icons.view",
      "maps.view",
      "multiLevel.view",
    ],
    Client_Admin: [
      "dashboard.view",
      "calendar.view",
      "email.view",
      "pages.view",
      "auth.view",
      "utility.view",
      "ui.view",
      "forms.view",
      "tables.view",
      "charts.view",
      "icons.view",
      "maps.view",
    ],
    Firm_Admin: [
      "dashboard.view",
      "calendar.view",
      "email.view",
      "auth.view",
      "utility.view",
      "ui.view",
      "forms.view",
      "tables.view",
      "charts.view",
      "icons.view",
      "maps.view",
    ],
  };
  